application: gae-endpoints-angular
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: templates/index.html
  upload: templates/index\.html
  secure: always

- url: /static
  static_dir: static

# setup partials static folder
- url: /partials
  static_dir: static/partials

# Endpoints handler: Must be /_ah/spi. Apps send requests to /_ah/api, but these are handled at /_ah/spi!!
# This code should be placed before main.app
- url: /_ah/spi/.*
  script: event_endpoints.APPLICATION

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest

# pycrypto library used for OAuth2 (required for authenticated APIs)
- name: pycrypto
  version: latest

- name: endpoints
  version: 1.0


